# Generated by Django 3.2.9 on 2022-08-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userscore', '0015_auto_20220304_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_score', models.FloatField(default=0)),
                ('level_id', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userscore.user')),
            ],
        ),
    ]
